name: Koda-Zero-Space-Build
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  Train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🚨 تنظيف عميق للسيرفر
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/share/powershell /usr/local/lib/node_modules
          sudo apt-get clean
          df -h # هيعرضلك المساحة الفاضية (هتلاقيها زادت جداً)
      - uses: actions/setup-python@v5
        with: {python-version: '3.10'}
      - name: 📦 تثبيت المكتبات
        run: pip install numpy torch transformers nltk
      - name: 🧠 الشفط والتدريب
        run: |
          python init_koda.py
          python main_brain.py
      - name: 💾 حفظ العقل
        uses: actions/upload-artifact@v4
        with:
          name: Koda-Ultra-Brain
          path: Koda_LLM/
